// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.2
// source: test.proto

package pb_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb_base "github.com/curio-research/keystone/test/proto/pb.base"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_Add         Operation = 0
	Operation_AddSpecific Operation = 1
	Operation_Remove      Operation = 2
	Operation_Update      Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "Add",
		1: "AddSpecific",
		2: "Remove",
		3: "Update",
	}
	Operation_value = map[string]int32{
		"Add":         0,
		"AddSpecific": 1,
		"Remove":      2,
		"Update":      3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// Reset gameState directly, ignore all game rules
type C2S_ResetGameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerList     []*pb_base.Player     `protobuf:"bytes,1,rep,name=PlayerList,proto3" json:"PlayerList,omitempty"`
	TileList       []*pb_base.Tile       `protobuf:"bytes,2,rep,name=TileList,proto3" json:"TileList,omitempty"`
	TroopStackList []*pb_base.TroopStack `protobuf:"bytes,3,rep,name=TroopStackList,proto3" json:"TroopStackList,omitempty"`
	BuildingList   []*pb_base.Building   `protobuf:"bytes,4,rep,name=BuildingList,proto3" json:"BuildingList,omitempty"`
}

func (x *C2S_ResetGameState) Reset() {
	*x = C2S_ResetGameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_ResetGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ResetGameState) ProtoMessage() {}

func (x *C2S_ResetGameState) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ResetGameState.ProtoReflect.Descriptor instead.
func (*C2S_ResetGameState) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *C2S_ResetGameState) GetPlayerList() []*pb_base.Player {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *C2S_ResetGameState) GetTileList() []*pb_base.Tile {
	if x != nil {
		return x.TileList
	}
	return nil
}

func (x *C2S_ResetGameState) GetTroopStackList() []*pb_base.TroopStack {
	if x != nil {
		return x.TroopStackList
	}
	return nil
}

func (x *C2S_ResetGameState) GetBuildingList() []*pb_base.Building {
	if x != nil {
		return x.BuildingList
	}
	return nil
}

// [blocking] Result of reset gameState
type S2C_ResetGameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerList     []*pb_base.Player     `protobuf:"bytes,1,rep,name=PlayerList,proto3" json:"PlayerList,omitempty"`
	TileList       []*pb_base.Tile       `protobuf:"bytes,2,rep,name=TileList,proto3" json:"TileList,omitempty"`
	TroopStackList []*pb_base.TroopStack `protobuf:"bytes,3,rep,name=TroopStackList,proto3" json:"TroopStackList,omitempty"`
	BuildingList   []*pb_base.Building   `protobuf:"bytes,4,rep,name=BuildingList,proto3" json:"BuildingList,omitempty"`
	Game           *pb_base.Game         `protobuf:"bytes,5,opt,name=Game,proto3" json:"Game,omitempty"`
}

func (x *S2C_ResetGameState) Reset() {
	*x = S2C_ResetGameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_ResetGameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ResetGameState) ProtoMessage() {}

func (x *S2C_ResetGameState) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ResetGameState.ProtoReflect.Descriptor instead.
func (*S2C_ResetGameState) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *S2C_ResetGameState) GetPlayerList() []*pb_base.Player {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

func (x *S2C_ResetGameState) GetTileList() []*pb_base.Tile {
	if x != nil {
		return x.TileList
	}
	return nil
}

func (x *S2C_ResetGameState) GetTroopStackList() []*pb_base.TroopStack {
	if x != nil {
		return x.TroopStackList
	}
	return nil
}

func (x *S2C_ResetGameState) GetBuildingList() []*pb_base.Building {
	if x != nil {
		return x.BuildingList
	}
	return nil
}

func (x *S2C_ResetGameState) GetGame() *pb_base.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

// Message used in integration test
type C2S_Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookInfos       []*TestBookInfo          `protobuf:"bytes,1,rep,name=bookInfos,proto3" json:"bookInfos,omitempty"`
	IdentityPayload *pb_base.IdentityPayload `protobuf:"bytes,2,opt,name=IdentityPayload,proto3" json:"IdentityPayload,omitempty"`
}

func (x *C2S_Test) Reset() {
	*x = C2S_Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Test) ProtoMessage() {}

func (x *C2S_Test) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Test.ProtoReflect.Descriptor instead.
func (*C2S_Test) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Test) GetBookInfos() []*TestBookInfo {
	if x != nil {
		return x.BookInfos
	}
	return nil
}

func (x *C2S_Test) GetIdentityPayload() *pb_base.IdentityPayload {
	if x != nil {
		return x.IdentityPayload
	}
	return nil
}

type TestBookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op     Operation `protobuf:"varint,1,opt,name=op,proto3,enum=pb_test.Operation" json:"op,omitempty"`
	Author string    `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title  string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Entity int64     `protobuf:"varint,4,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *TestBookInfo) Reset() {
	*x = TestBookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestBookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestBookInfo) ProtoMessage() {}

func (x *TestBookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestBookInfo.ProtoReflect.Descriptor instead.
func (*TestBookInfo) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *TestBookInfo) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_Add
}

func (x *TestBookInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *TestBookInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TestBookInfo) GetEntity() int64 {
	if x != nil {
		return x.Entity
	}
	return 0
}

type S2C_Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity int64 `protobuf:"varint,1,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *S2C_Test) Reset() {
	*x = S2C_Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Test) ProtoMessage() {}

func (x *S2C_Test) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Test.ProtoReflect.Descriptor instead.
func (*S2C_Test) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *S2C_Test) GetEntity() int64 {
	if x != nil {
		return x.Entity
	}
	return 0
}

var File_test_proto protoreflect.FileDescriptor

var file_test_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62,
	0x5f, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe4, 0x01, 0x0a, 0x12, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x65, 0x73, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x54, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x54, 0x69, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61,
	0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x63,
	0x6b, 0x52, 0x0e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x35, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x87, 0x02, 0x0a, 0x12, 0x53, 0x32, 0x43,
	0x5f, 0x52, 0x65, 0x73, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x2f, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x08, 0x54, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x54, 0x69, 0x6c,
	0x65, 0x52, 0x08, 0x54, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x54,
	0x72, 0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x54, 0x72,
	0x6f, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x0e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x53,
	0x74, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x47, 0x61,
	0x6d, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x43, 0x32, 0x53, 0x5f, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x73,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x12, 0x42, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x62, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x78, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x22, 0x22, 0x0a, 0x08, 0x53, 0x32, 0x43, 0x5f, 0x54, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2a, 0x3d, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x62, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData = file_test_proto_rawDesc
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_proto_rawDescData)
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_proto_goTypes = []interface{}{
	(Operation)(0),                  // 0: pb_test.Operation
	(*C2S_ResetGameState)(nil),      // 1: pb_test.C2S_ResetGameState
	(*S2C_ResetGameState)(nil),      // 2: pb_test.S2C_ResetGameState
	(*C2S_Test)(nil),                // 3: pb_test.C2S_Test
	(*TestBookInfo)(nil),            // 4: pb_test.TestBookInfo
	(*S2C_Test)(nil),                // 5: pb_test.S2C_Test
	(*pb_base.Player)(nil),          // 6: pb_base.Player
	(*pb_base.Tile)(nil),            // 7: pb_base.Tile
	(*pb_base.TroopStack)(nil),      // 8: pb_base.TroopStack
	(*pb_base.Building)(nil),        // 9: pb_base.Building
	(*pb_base.Game)(nil),            // 10: pb_base.Game
	(*pb_base.IdentityPayload)(nil), // 11: pb_base.IdentityPayload
}
var file_test_proto_depIdxs = []int32{
	6,  // 0: pb_test.C2S_ResetGameState.PlayerList:type_name -> pb_base.Player
	7,  // 1: pb_test.C2S_ResetGameState.TileList:type_name -> pb_base.Tile
	8,  // 2: pb_test.C2S_ResetGameState.TroopStackList:type_name -> pb_base.TroopStack
	9,  // 3: pb_test.C2S_ResetGameState.BuildingList:type_name -> pb_base.Building
	6,  // 4: pb_test.S2C_ResetGameState.PlayerList:type_name -> pb_base.Player
	7,  // 5: pb_test.S2C_ResetGameState.TileList:type_name -> pb_base.Tile
	8,  // 6: pb_test.S2C_ResetGameState.TroopStackList:type_name -> pb_base.TroopStack
	9,  // 7: pb_test.S2C_ResetGameState.BuildingList:type_name -> pb_base.Building
	10, // 8: pb_test.S2C_ResetGameState.Game:type_name -> pb_base.Game
	4,  // 9: pb_test.C2S_Test.bookInfos:type_name -> pb_test.TestBookInfo
	11, // 10: pb_test.C2S_Test.IdentityPayload:type_name -> pb_base.IdentityPayload
	0,  // 11: pb_test.TestBookInfo.op:type_name -> pb_test.Operation
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_ResetGameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_ResetGameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestBookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_rawDesc = nil
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
